---
title: "About"
---

## Education

Columbia University \| New York, NY \| M.S in Biostatistics \| 2024-Present

Virginia Tech \| Blacksburg, VA \| B.S in Statistics and B.S in Mathematics \| 2020-2024

## Experience
### BayesTPC (2022-Present)
Developer and current maintainer of [**bayesTPC**](https://github.com/johnwilliamsmithjr/bayesTPC): an R package to easily fit Bayesian thermal performance curves using MCMC.

### VectorByte (2022-2024)

Contributed to the [VectorByte](https://www.vectorbyte.org/) open Vectraits database for biological trait data. Fit Bayesian TPCs to trait data for different mosquito species. Taught Bayesian methods to infectious disease researchers.

### Teaching

Was a UTA for STAT3654: Intro to Data Analytics and Visualization taught at Virginia Tech in Summer 2023. Also tutored coursework in single and multi-variable calculus, linear algebra, and precalculus to groups of 100+ students.

### Volunteering

Performed over 100 hours of ecological conservation field work as a member of Lambda Iota Mu in Southwest VA. Duties involved invasive species removal, trail building, preservation of local wetlands, etc.