project:
  type: website
  output-dir: pages
website:
  navbar:
    background: "#630031"
    foreground: "light"
    title: "BayesTPC"
    left:
      - text: "Home"
        href: index.html
      - text: "Examples"
        href: examples.html
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

